[package]
name = "win_state_diag"
version = "0.4.0"
edition = "2024"
authors = ["EXPC Design and Production"]
description = "Portable Windows state diagnostic center"
publish = false

[dependencies]
egui = "0.36"
eframe = "0.36"

[build-dependencies]
winresource = "0.1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"



